export const SET_CHECKOUT_ERRORS = "SET_CHECKOUT_ERRORS";

export const SET_CHECKOUT_STAGE_SHIPPING = "SET_CHECKOUT_STAGE_SHIPPING";
export const SET_CHECKOUT_SHIPPING_INDEX = "SET_CHECKOUT_SHIPPING_INDEX";
export const RESET_CHECKOUT_STAGE = "RESET_CHECKOUT_STAGE";
