export const REFRESH_USER_STATE = "REFRESH_USER_STATE";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_NOT_FOUND = "GET_USER_NOT_FOUND";

export const SIGNIN_FAIL = "SIGNIN_FAILED";

export const LOGIN_WITH_EMAIL_SUCCESS = "LOGIN_WITH_EMAIL_SUCCESS";
export const LOGIN_WITH_EMAIL_FAIL = "LOGIN_WITH_EMAIL_FAILED";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
