export const SET_USER_LOADING_TRUE = "SET_USER_LOADING_TRUE";
export const SET_USER_ERRORS = "SET_USER_ERRORS";

export const GET_USER_SUCCESS = "GET_USER_SUCCESS";

// export const SIGNIN_FAIL = "SIGNIN_FAILED";
export const SIGNIN_VIA_EMAIL_PASS_SUCCESS = "SIGNIN_VIA_EMAIL_PASS_SUCCESS";

export const LOGIN_VIA_EMAIL_PASS_SUCCESS = "LOGIN_VIA_EMAIL_PASS_SUCCESS";

// export const UPDATE_USER

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
