export const REFRESH_USER_STATE = "REFRESH_USER_STATE";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_NOT_FOUND = "GET_USER_NOT_FOUND";

// export const SIGNIN_FAIL = "SIGNIN_FAILED";
export const SIGNIN_VIA_EMAIL_PASS_SUCCESS = "SIGNIN_VIA_EMAIL_PASS_SUCCESS";
export const SIGNIN_VIA_EMAIL_PASS_FAIL = "SIGNIN_VIA_EMAIL_PASS_FAILED";

export const LOGIN_VIA_EMAIL_PASS_SUCCESS = "LOGIN_VIA_EMAIL_PASS_SUCCESS";
export const LOGIN_VIA_EMAIL_PASS_FAIL = "LOGIN_VIA_EMAIL_PASS_FAILED";

// export const UPDATE_USER

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
