export const GET_SHIPPING_DETAILS_REQUEST = "GET_SHIPPING_DETAILS_REQUEST";
export const GET_SHIPPING_DETAILS_SUCCESS = "GET_SHIPPING_DETAILS_SUCCESS";
export const GET_SHIPPING_DETAILS_FAIL = "GET_SHIPPING_DETAILS_FAILED";
