export const SET_SHIPPING_LOADING_TRUE = "SET_SHIPPING_LOADING_TRUE";
export const SET_SHIPPING_ERRORS = "SET_SHIPPING_ERRORS";

export const GET_SHIPPING_DETAILS_SUCCESS = "GET_SHIPPING_DETAILS_SUCCESS";

export const ADD_SHIPPING_DETAILS_SUCCESS = "ADD_SHIPPING_DETAILS_SUCCESS";

export const EDIT_SHIPPING_DETAILS_SUCCESS = "EDIT_SHIPPING_DETAILS_SUCCESS";
