export const SET_SHIPPING_LOADING_TRUE = "SET_SHIPPING_LOADING_TRUE";
export const SET_SHIPPING_ERRORS = "SET_SHIPPING_ERRORS";

export const GET_SHIPPING_DETAILS_SUCCESS = "GET_SHIPPING_DETAILS_SUCCESS";

export const SAVE_SHIPPING_DETAILS_SUCCESS = "SAVE_SHIPPING_DETAILS_SUCCESS";
