export const SET_CART_LOADING_TRUE = "SET_CART_LOADING_TRUE";
export const SET_CART_ERRORS = "SET_CART_ERRORS";

export const GET_CART_SUCCESS = "GET_CART_SUCCESS";

export const SAVE_TO_CART_SUCCESS = "SAVE_TO_CART_SUCCESS";

export const DELETE_FROM_CART_SUCCESS = "DELETE_FROM_CART_SUCCESS";
