export const GET_CART_REQUEST = "GET_CART_REQUEST";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_FAIL = "GET_CART_FAILED";

export const SAVE_TO_CART_SUCCESS = "SAVE_TO_CART_SUCCESS";
export const SAVE_TO_CART_FAIL = "SAVE_TO_CART_FAILED";
