export const SET_ORDER_LOADING_TRUE = "SET_ORDER_LOADING_TRUE";
export const SET_ORDER_ERRORS = "SET_ORDER_ERRORS";

export const GET_ORDER_HISTORY_SUCCESS = "GET_ORDER_HISTORY_SUCCESS";

export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
